# -*- coding: utf-8 -*-
"""data cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUcWWDeGcceaT1mZuv9RBTvJefT1t2Qt
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/marketing_campaign.csv', sep='\t')
data

data.isnull().sum()

data.describe()

data['Income'].fillna(data['Income'].mean(), inplace=True)

data.isnull().sum()

duplicated_rows = data[data.duplicated(subset=['ID'])]
duplicated_rows

data['Education'].str.title()

data['Dt_Customer'] = pd.to_datetime(data['Dt_Customer'], format='%d-%m-%Y')
display(data.head())

data.columns = data.columns.str.replace('  ', '_')
display(data.columns)

## check and fix data types
data.info()

#fix data types
data['Income'] = data['Income'].astype(int)
data.info()

