# -*- coding: utf-8 -*-
"""day 6 task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJWjyX-nlnr2ibpdgmAnSVEbrPhB1Y4_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = df = pd.read_excel("/content/global_superstore_2016.xlsx")
data

data.head()

data.info()

data.describe()

data.isnull().sum()

data['Sub-Category'].value_counts()

sns.pairplot(data)
plt.show()

"""The pairplot shows scatter plots between all numeric variables.

You can see a positive trend between Sales and Profit, and Sales and Shipping Cost.

The plot between Discount and Profit shows a downward pattern, confirming that higher discounts reduce profits.

Most variables like Quantity, Row ID, and Postal Code do not show any clear trend.
"""

numerical_data = data.select_dtypes(include=np.number)
sns.heatmap(numerical_data.corr(), annot=True, cmap='coolwarm')
plt.show()

"""The heatmap shows how numerical columns are related to each other.

Sales and Shipping Cost have a strong positive correlation (0.77) — when sales increase, shipping cost also rises.

Sales and Profit show a moderate positive correlation (0.48) — higher sales often lead to higher profits.

Discount and Profit have a negative correlation (-0.32) — more discount usually means less profit.

Other variables have very low correlation, meaning they don’t strongly affect each other.
"""

numerical_data = data.select_dtypes(include=np.number)
numerical_data.skew()

sns.scatterplot(x='Sales', y='Profit', data=df)
plt.title("Sales vs Profit")
plt.show()

"""The scatter plot shows how Sales and Profit are related.

As Sales increase, Profit doesn’t always increase — many points are below zero, meaning losses occur even with high sales.

The plot shows a wide spread, especially for higher sales values, meaning profit varies a lot.

Some points are far below (around -2000), showing big losses in a few cases.

Overall, the relationship between Sales and Profit seems weak or negative — higher sales do not always mean higher profit.
"""

sns.boxplot(x='Sub-Category', y='Profit', data=df)
plt.title("Sub-Categoryy vs Profit")
plt.figure(figsize=(18, 12))  # 🔹 Adjust figure size (auto based on data width)
sns.boxplot(x='Sub-Category', y='Sales', data=df)
plt.title("Sub-Category vs Region")
plt.xticks(rotation=45)      # 🔹 Rotate x-labels to prevent overlap

"""# **Sales by Sub-Category**

Copiers and Machines have the highest sales on average.

Phones, Chairs, and Bookcases also show good sales levels.

Fasteners, Labels, and Envelopes have the lowest sales.

Some categories like Binders, Art, Paper, and Appliances show a few very high sales values (outliers).

Tables and Copiers have large variation in sales, while Labels and Envelopes have very small variation.

Many categories show right skewness meaning most sales are small, but a few are very high.

Overall, Copiers and Machines perform the best, while Fasteners and Labels perform the least.

# **Summary of Findings**
**1️ Data Overview**

The dataset contains 51,290 records and 24 columns.

It includes details about orders, customers, products, sales, profit, and shipping.

Most columns are complete, except Postal Code, which has some missing values.

**2️ Descriptive Statistics**

Sales and Profit values vary widely across transactions.

Discounts mostly range between 0.1 to 0.8, and Quantity ranges from 1 to 14 items per order.

**3️ Missing Values**

Only the Postal Code column has missing values.

Other columns have no missing data, so the dataset is mostly clean.

**4️ Correlation Analysis (Heatmap)**

Sales and Shipping Cost are strongly correlated (0.77) — higher sales mean higher shipping cost.

Sales and Profit show a moderate positive correlation (0.48) — higher sales generally improve profit.

Discount and Profit are negatively correlated (-0.32) — more discount leads to less profit.

**5️ Pairplot (Relationships)**

Sales, Profit, and Shipping Cost show positive relationships.

Discount and Profit show a negative trend.

Other numeric variables (like Quantity, Row ID, Postal Code) show no clear relationship.

6️ **Sales vs Profit (Scatter Plot)**

Higher sales don’t always mean higher profit — some large sales even cause losses.

The relationship between Sales and Profit is weak and scattered.

Some orders have large negative profits (losses over ₹2000).

7️. **Sales by Sub-Category (Box Plot)**

Copiers and Machines show the highest average sales.

Fasteners, Labels, and Envelopes have lowest sales.

Many sub-categories show right-skewed patterns (a few very large sales).

Tables and Copiers show wide variation, while Labels and Envelopes are more consistent.

# Overall Insights

High sales are linked with higher shipping costs and better profit, but discounts reduce profit.

Not all high-sales products are profitable — pricing and discount strategy affect performance.

Focus areas for growth: reduce discounts, optimize shipping costs, and improve margins for low-profit categories.
"""